# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mYNTc7-B9ERcoSeRZb-1dQ4wmYO3NTnO
"""

# Student Performance Prediction System
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

# Sample Dataset
data = {
    'study_hours': [2,4,6,8,3,5,7,9,1,6],
    'attendance': [60,70,80,90,65,75,85,95,50,80],
    'prev_score': [45,55,65,75,50,60,70,80,40,68],
    'performance': ['Poor','Average','Good','Excellent',
                    'Poor','Average','Good','Excellent',
                    'Poor','Good']
}

df = pd.DataFrame(data)

# Encode target
le = LabelEncoder()
df['performance'] = le.fit_transform(df['performance'])

# Features & Target
X = df[['study_hours','attendance','prev_score']]
y = df['performance']

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

# Model
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Accuracy
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Model trained successfully!")

# AI-Powered Job Recommendation Portal
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Sample Data
jobs = pd.DataFrame({
    'job_id': [1, 2, 3, 4, 5],
    'title': [
        'Python Developer',
        'Data Scientist',
        'ML Engineer',
        'Web Developer',
        'AI Researcher'
    ],
    'skills_required': [
        'python django flask rest api',
        'python machine learning pandas numpy scikit-learn',
        'python tensorflow keras deep learning',
        'javascript react html css nodejs',
        'python nlp transformers bert research'
    ]
})

# Job Seeker Profile
seeker_profile = "python machine learning scikit-learn flask"

# TF-IDF Vectorization
tfidf = TfidfVectorizer()
job_matrix = tfidf.fit_transform(jobs['skills_required'])
seeker_vector = tfidf.transform([seeker_profile])

# Cosine Similarity
similarity_scores = cosine_similarity(seeker_vector, job_matrix)[0]
jobs['match_score'] = (similarity_scores * 100).round(2)

# Top Recommendations
recommended = jobs.sort_values('match_score', ascending=False)

print("🎯 Job Recommendations for You:")
print("="*40)
for _, row in recommended.iterrows():
    print(f"✅ {row['title']} — Match: {row['match_score']}%")
